[package]
name = "native-webview"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[[bin]]
name = "native-webview"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.7" }
# web-view = { version = "0.7", features = ["edge"] }
